### ISSUE TITLE
Impossible to remove `localhost` from `ignoredHostnames`

### ISSUE THREAD

**Issue by obulat** [nuxt-modules/plausible#30]
## Description

The `trackLocalhost` option is deprecated, but the new way of setting this as `ignoredHostnames: []` doesn't work.

"localhost" is always added to the `ignoredHostnames` array in the module setup. 

When I added a log at the top of the setup, I see that `options.ignoredHostnames` array always contains "localhost". If you set the value of `ignoredHostnames` to something else, like `["none"]`, then this value is _added_ to the default `["localhost"]` array instead of replacing it.

**Comment by johannschopplich** [comment]
Good catch! Thanks a lot. I have just released v1.0.1 to fix this issue. You can now provide an empty `ignoredHostnames` array to allow localhost for tracking:

```ts
export default defineNuxtConfig({
  modules: ['@nuxtjs/plausible'],

  plausible: {
    ignoredHostnames: [],
  },
})
```

**Comment by obulat** [comment]
Thank you for the quick fix and release!

**Comment by obulat** [comment]
This did not fix the problem. I tried updating the module to v1.0.1 and replacing `trackLocalhost` with `ignoredHostnames`, and all of the analytics e2e tests failed, see [this CI run](https://github.com/WordPress/openverse/actions/runs/10250122171/job/28355208871?pr=4716). When I added `trackLocalhost` back, they [passed](https://github.com/WordPress/openverse/actions/runs/10260245561/job/28386045331?pr=4716).

After updating, the plugin types also broke: I had to manually add the types that were previously created by Nuxt automatically. This might be related to the "_The inferred type of 'default' cannot be named without a reference to .._." warnings in the `release` action run for v1.0.1: https://github.com/nuxt-modules/plausible/actions/runs/10229250370
Would using a function for module defaults fix it?

**Comment by johannschopplich** [comment]
@obulat Thanks a lot for the follow-up. Indeed, the plugin types where broken as of recent changes to the Nuxt module builder. This should be fixed with v1.0.2. 

Also, `ignoredHostnames: []` should now work as intended... Please upgrade to the latest version and give me a hint if it worked out for ya. Thanks!

**Comment by obulat** [comment]
Thank you again for quick fix and release, @johannschopplich ! It's really fixed now, and we are about to migrate to the latest version :)
